name: Deploy Lambda Function

on:
  push:
    paths:
      - userguide.md

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Lambda
        run: echo "Deploying Lambda function..."
